### PR TITLE
Update to go1.17

### PR DESCRIPTION
**Pull request by chrisdoherty4**
As discussed in the community meeting: this updates the go.mod to use 1.17 keeping up-to-date with the times.

### CODE REVIEW

**Review by mmlb — APPROVED** [review]
lgtm, thanks!

**Comment by chrisdoherty4** [comment]
@mmlb Looks like mergify isn't setup for this repository. Can you push it in?

**Comment by mmlb** [comment]
It is setup but maybe badly? https://github.com/tinkerbell/terraform-provider-tinkerbell/pull/30/checks?check_run_id=6260571365

**Comment by mmlb** [comment]
Hmm I think we can recreate the path based skips in mergify's config too.

**Review by displague — APPROVED** [review]

**Comment by displague** [comment]
The linter is not happy.

**Comment by chrisdoherty4** [comment]
I'll try circling round to fix this in due course.

**Review by displague — APPROVED** [review]

**Pull request merged**
